"""initial schema

Revision ID: a08768e87412
Revises:
Create Date: 2026-09-12 20:04:11.549226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.types

# revision identifiers, used by Alembic.
revision: str = "a08768e87412"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tables that carry practice_id and must be tenant-isolated via RLS.
TENANT_TABLES = ("users", "sessions", "transcripts", "notes", "consents", "audit_logs")

# Dev-only placeholder credential for the restricted application role. See
# README ("Database roles and RLS") before this pattern goes anywhere near
# a real environment — production must provision/rotate this via a secrets
# manager, not a hardcoded migration literal.
APP_ROLE = "docflow_app"
APP_ROLE_PASSWORD = "docflow_app_dev_only"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practices",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "specialty", sa.String(length=100), server_default="primary_care", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="practice_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practices")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("owner", "clinician", "staff", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_users_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_practice_id"), "users", ["practice_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("create", "read", "update", "delete", "export", name="audit_action"),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_audit_logs_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_practice_id"), "audit_logs", ["practice_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "recording",
                "transcribing",
                "generating",
                "complete",
                "error",
                name="session_status",
            ),
            server_default="created",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("patient_ref", app.db.types.PHIText(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["users.id"],
            name=op.f("fk_sessions_clinician_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_sessions_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_clinician_id"), "sessions", ["clinician_id"], unique=False)
    op.create_index(op.f("ix_sessions_practice_id"), "sessions", ["practice_id"], unique=False)
    op.create_table(
        "consents",
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column(
            "consent_type",
            sa.Enum("recording", "retention", "training", name="consent_type"),
            nullable=False,
        ),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("granted_by", sa.String(length=255), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_consents_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_consents_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_index(op.f("ix_consents_practice_id"), "consents", ["practice_id"], unique=False)
    op.create_index(op.f("ix_consents_session_id"), "consents", ["session_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.String(length=50), server_default="soap", nullable=False),
        sa.Column("subjective", app.db.types.PHIText(), nullable=True),
        sa.Column("objective", app.db.types.PHIText(), nullable=True),
        sa.Column("assessment", app.db.types.PHIText(), nullable=True),
        sa.Column("plan", app.db.types.PHIText(), nullable=True),
        sa.Column("full_text", app.db.types.PHIText(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "final", name="note_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_notes_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_notes_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index(op.f("ix_notes_practice_id"), "notes", ["practice_id"], unique=False)
    op.create_index(op.f("ix_notes_session_id"), "notes", ["session_id"], unique=False)
    op.create_table(
        "transcripts",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("content", app.db.types.PHIText(), nullable=False),
        sa.Column(
            "segments", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("is_retained", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_transcripts_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_transcripts_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
        sa.UniqueConstraint("session_id", name=op.f("uq_transcripts_session_id")),
    )
    op.create_index(
        op.f("ix_transcripts_practice_id"), "transcripts", ["practice_id"], unique=False
    )
    # ### end Alembic commands ###

    # --- Restricted application role -----------------------------------
    # Non-superuser, NOBYPASSRLS: this is what actually makes the RLS
    # policies below bite. The migration itself runs as the admin/owner
    # role (Settings.DATABASE_URL), which is a superuser in local dev and
    # would silently bypass RLS if the app connected as it too.
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                    CREATE ROLE {APP_ROLE} LOGIN PASSWORD '{APP_ROLE_PASSWORD}'
                        NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
                END IF;
            END
            $$;
            """
        )
    )
    op.execute(sa.text(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}"))
    op.execute(
        sa.text(
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON "
            f"practices, {', '.join(TENANT_TABLES)} TO {APP_ROLE}"
        )
    )
    # Immutability, database level: the app role can create and read audit
    # rows but never alter or erase them. (App-level enforcement also
    # exists — see app/models/audit_log.py — but only this REVOKE holds up
    # against anything that talks to Postgres directly as this role.)
    op.execute(sa.text(f"REVOKE UPDATE, DELETE ON audit_logs FROM {APP_ROLE}"))

    # --- Row-Level Security: practice-scoped tenant isolation -----------
    # FORCE (not just ENABLE) is required because in Postgres the *table
    # owner* bypasses RLS by default even with ENABLE alone; the migration
    # role owns these tables, so without FORCE this policy would be a
    # no-op for that role. Real Postgres superusers bypass RLS regardless
    # of FORCE — hence the dedicated non-superuser app role above.
    for table in TENANT_TABLES:
        op.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
        op.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
        op.execute(
            sa.text(
                f"""
                CREATE POLICY tenant_isolation_policy ON {table}
                    USING (practice_id::text = current_setting('app.current_practice_id', true))
                    WITH CHECK (practice_id::text = current_setting('app.current_practice_id', true))
                """
            )
        )


def downgrade() -> None:
    # RLS policies and grants are dropped implicitly when their tables are
    # dropped below; nothing extra needed for those. We deliberately do
    # NOT `DROP ROLE docflow_app` here: roles are cluster-wide (not
    # per-database), so another database in the same cluster (e.g. a
    # parallel test database) may still depend on it. Role removal is a
    # manual/ops action, not something a schema downgrade should do.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcripts_practice_id"), table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_index(op.f("ix_notes_session_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_practice_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_consents_session_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_practice_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_sessions_practice_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_clinician_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_audit_logs_practice_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_practice_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("practices")
    # ### end Alembic commands ###

    # Postgres native ENUM types are NOT dropped automatically by
    # op.drop_table for the columns that used them — left in place they'd
    # collide with CREATE TYPE on the next upgrade.
    for enum_name in (
        "practice_status",
        "user_role",
        "session_status",
        "note_status",
        "consent_type",
        "audit_action",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
