"""auth: refresh tokens, mfa secret, auth audit actions

Revision ID: a2dfb9c3f006
Revises: a08768e87412
Create Date: 2026-09-12 20:41:50.517215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types

# revision identifiers, used by Alembic.
revision: str = "a2dfb9c3f006"
down_revision: Union[str, None] = "a08768e87412"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

APP_ROLE = "docflow_app"

# New AuditAction values (Phase 3 auth events). Postgres has no "ALTER
# TYPE ... ADD VALUE IF NOT EXISTS" prior to PG12 semantics quirks around
# transactions, but PG16 supports plain ADD VALUE inside a transaction as
# long as the new value isn't *used* in that same transaction — which this
# migration doesn't do.
NEW_AUDIT_ACTIONS = (
    "register",
    "login_success",
    "login_failure",
    "logout",
    "mfa_enrolled",
    "mfa_verified",
    "token_reuse_detected",
)
ORIGINAL_AUDIT_ACTIONS = ("create", "read", "update", "delete", "export")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_refresh_tokens_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name=op.f("uq_refresh_tokens_jti")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_practice_id"), "refresh_tokens", ["practice_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.add_column("users", sa.Column("mfa_secret", app.db.types.PHIText(), nullable=True))
    # ### end Alembic commands ###

    # --- refresh_tokens: RLS + grants, same shape as every other tenant
    # table (see the initial migration's "Row-Level Security" section for
    # why FORCE is required and why the app role must be non-superuser).
    op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE, DELETE ON refresh_tokens TO {APP_ROLE}"))
    op.execute(sa.text("ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text("ALTER TABLE refresh_tokens FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            """
            CREATE POLICY tenant_isolation_policy ON refresh_tokens
                USING (practice_id::text = current_setting('app.current_practice_id', true))
                WITH CHECK (practice_id::text = current_setting('app.current_practice_id', true))
            """
        )
    )

    # --- Auth audit actions -------------------------------------------
    for action in NEW_AUDIT_ACTIONS:
        op.execute(sa.text(f"ALTER TYPE audit_action ADD VALUE '{action}'"))


def downgrade() -> None:
    # Shrink audit_action back to its original value set. Postgres has no
    # "ALTER TYPE ... DROP VALUE"; the standard workaround is to swap in a
    # freshly created type with the original values. This fails loudly
    # (as it should) if any audit_logs row still uses one of the values
    # being removed — silently corrupting that data would be worse.
    original_list = ", ".join(f"'{a}'" for a in ORIGINAL_AUDIT_ACTIONS)
    op.execute(sa.text("ALTER TYPE audit_action RENAME TO audit_action_old"))
    op.execute(sa.text(f"CREATE TYPE audit_action AS ENUM ({original_list})"))
    op.execute(
        sa.text(
            "ALTER TABLE audit_logs ALTER COLUMN action TYPE audit_action "
            "USING action::text::audit_action"
        )
    )
    op.execute(sa.text("DROP TYPE audit_action_old"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mfa_secret")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_practice_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
